# request constants
uint8 FORWARD_TYPE=0
uint8 SUBSCRIBE_TYPE=1
uint8 UNSUBSCRIBE_TYPE=2
uint8 HELLO_TYPE=3
uint8 GOODBYE_TYPE=4
# request fileds
uint8 type
string topic
string payload
---
# response constants
uint8 ACK=0
uint8 FAILED=1
# response fileds
uint8 status_code